### ISSUE TITLE
Возможно убрать инлайновые js комментарии в подключаемом коде?

### ISSUE THREAD

**Issue by pu6elozed** [CleanTalk/bitrix-antispam#15]
Кейс: у проекта на событии OnEndBufferContent выполняется очистка от пробелов/табов/разрывов строки.
Проблема: инлайновые комментарии наподобие [такого](https://github.com/CleanTalk/bitrix-antispam/blob/dev/cleantalk.antispam/include.php#L996) не позволяют выполняться последующему коду модуля.
Предлагаемые варианты решения: 
1. использовать многострочный комментарий на одной строке `/* comment */`
2. вынести комментарии в php чтобы они были: и информативны и не влияли на рендер
3. отказаться от комментирования в этом куске кода (крайняя мера)

**Comment by davydovct** [comment]
Добрый день,

Спасибо, изменили формат комментариев тут
https://github.com/CleanTalk/bitrix-antispam/commit/a0e3c9c2fb56a4544cf1ee59e59ed434b7461840
